## 2주차 과제

1. NumPy 배열 생성 및 연산
- NumPy를 사용해 3x3 정수 배열(1부터 9까지)과 2x5 실수 배열(0~1 사이 난수)을 생성하세요. 생성한 배열의 합계와 평균을 각각 계산하고, 두 배열을 곱한 결과를 출력하세요.
- 배열의 형태를 유지하지 않아도 괜찮습니다.

In [ ]:
import numpy as np

# 3x3 정수 배열 (1부터 9까지)
array1 = np.arange(1, 10).reshape(3, 3)

# 합계 및 평균 계산
sum_array1 = np.sum(array1)
mean_array1 = np.mean(array1)

# 결과 출력
print("3x3 정수 배열:")
print(array1)
print(f"\n합계: {sum_array1}")
print(f"평균: {mean_array1}")

print("-" * 60)  # 밑줄 추가

# 2x5 실수 배열 (0~1 사이 난수)
array2 = np.random.rand(2, 5)

# 합계 및 평균 계산
sum_array2 = np.sum(array2)
mean_array2 = np.mean(array2)

# 결과 출력
print("2x5 실수 배열:")
print(array2)
print(f"\n합계: {sum_array2:.4f}")
print(f"평균: {mean_array2:.4f}")

print("-" * 60)  # 밑줄 추가

ab_array = np.outer(array1.flatten() , array2.flatten())
print('array1배열과 array2배열의 곱:')
print(ab_array)



3x3 정수 배열:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

합계: 45
평균: 5.0
------------------------------------------------------------
2x5 실수 배열:
[[0.83567341 0.94323056 0.61442628 0.66113906 0.60374699]
 [0.60416596 0.25860921 0.03329936 0.8276057  0.19987487]]

합계: 5.5818
평균: 0.5582
------------------------------------------------------------
array1배열과 array2배열의 곱:
[[0.83567341 0.94323056 0.61442628 0.66113906 0.60374699 0.60416596
  0.25860921 0.03329936 0.8276057  0.19987487]
 [1.67134682 1.88646113 1.22885256 1.32227811 1.20749398 1.20833191
  0.51721842 0.06659871 1.6552114  0.39974974]
 [2.50702023 2.82969169 1.84327884 1.98341717 1.81124096 1.81249787
  0.77582764 0.09989807 2.4828171  0.5996246 ]
 [3.34269364 3.77292225 2.45770513 2.64455622 2.41498795 2.41666382
  1.03443685 0.13319742 3.3104228  0.79949947]
 [4.17836706 4.71615281 3.07213141 3.30569528 3.01873494 3.02082978
  1.29304606 0.16649678 4.13802849 0.99937434]
 [5.01404047 5.65938338 3.68655769 3.96683433 3.62248193 3.62499573
  1.55

---
2. Pandas를 활용한 데이터 처리
- 아래 데이터를 DataFrame으로 생성하세요.
Name: [Alice, Bob, None, Charlie]
Age: [25, None, 28, 35]
City: [New York, None, Chicago, None]

- 누락된 이름은 "Unknown"으로, 나이는 평균 나이로 채우고 수정된 DataFrame을 출력하세요.

In [ ]:
import pandas as pd

# 데이터 생성
data = {
    'Name': ['Alice', 'Bob', None, 'Charlie'],
    'Age': [25, None, 28, 35],
    'City': ['New York', None, 'Chicago', None]
}

df = pd.DataFrame(data)

# 수정 전 데이터 정보 출력
print("Before Processing:")
df.info()
print("\n")

# 누락된 데이터 처리
df["Name"].fillna("Unknown")
df["Age"].fillna(df["Age"].mean()).astype(int)

print("-" * 60)  # 밑줄 추가

# 수정된 데이터 출력
print(df)


Before Processing:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    3 non-null      object 
 1   Age     3 non-null      float64
 2   City    2 non-null      object 
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes


------------------------------------------------------------
      Name   Age      City
0    Alice  25.0  New York
1      Bob   NaN      None
2     None  28.0   Chicago
3  Charlie  35.0      None


3. HTTP 통신을 활용한 데이터 읽기 및 저장
- https://jsonplaceholder.typicode.com/todos 에서 JSON 데이터를 가져오세요.
데이터를 파일로 저장한 뒤, "title" 키의 값을 출력하세요.

In [ ]:
import requests
import pandas as pd


url = "https://jsonplaceholder.typicode.com/todos"
data = requests.get(url).json()

df = pd.DataFrame(data)
df.to_csv("todos.csv")

print(df["title"])


0                                     delectus aut autem
1                     quis ut nam facilis et officia qui
2                                    fugiat veniam minus
3                                       et porro tempora
4      laboriosam mollitia et enim quasi adipisci qui...
                             ...                        
195                  consequuntur aut ut fugit similique
196                    dignissimos quo nobis earum saepe
197                         quis eius est sint explicabo
198                         numquam repellendus a magnam
199                         ipsam aperiam voluptates qui
Name: title, Length: 200, dtype: object
